### PR TITLE
feat(version): read app info from package.json

### PR DESCRIPTION
**Pull request by AvinashReddy3108**
Basically, an extension of [this commit](https://github.com/borjapazr/express-typescript-skeleton/commit/75526e8cbd010e9d2884330725ec7d0e4be0e833) for other applicable fields in the `AppInfo` array.

### CODE REVIEW

**Comment by AvinashReddy3108** [comment]
One possible extensions to this PR

- populate `AppInfo` fields only from package.json .. like so (also removing related variables from the `.env` file)
```typescript
const AppInfo = {
  APP_VERSION: readPackageJsonSync().version,
  APP_NAME: readPackageJsonSync().name,
  APP_DESCRIPTION: readPackageJsonSync().description,
  AUTHOR_NAME: readPackageJsonSync().author?.name,
  AUTHOR_EMAIL: readPackageJsonSync().author?.email,
  AUTHOR_WEBSITE: readPackageJsonSync().author?.url
};
```

But I was hesitant to make this change for now as I don't know the reason behind you using environment variables for these stuff..

**Comment by borjapazr** [comment]
> One possible extensions to this PR
> 
> * populate `AppInfo` fields only from package.json .. like so (also removing related variables from the `.env` file)
> 
> ```ts
> const AppInfo = {
>   APP_VERSION: readPackageJsonSync().version,
>   APP_NAME: readPackageJsonSync().name,
>   APP_DESCRIPTION: readPackageJsonSync().description,
>   AUTHOR_NAME: readPackageJsonSync().author?.name,
>   AUTHOR_EMAIL: readPackageJsonSync().author?.email,
>   AUTHOR_WEBSITE: readPackageJsonSync().author?.url
> };
> ```
> 
> But I was hesitant to make this change for now as I don't know the reason behind you using environment variables for these stuff..

Hi @AvinashReddy3108 ! First of all, thank you for your PR. I think it is a very good idea 👌 Anyway, before merge the PR it is necessary to correct the problems reported by tsc.

The environment variables are there to provide an option to overwrite all this information. For example, imagine that when you are going to deploy the application in a productive environment you prefer to show the information of the company and not of the developer who implemented the application. In this way, unless overwritten, the package.json data will always be shown, but if we want others for any reason, they could be provided in a very simple way.

**Comment by AvinashReddy3108** [comment]
> Anyway, before merge the PR it is necessary to correct the problems reported by tsc.
Never faced those issues in my local machine (node 18.x), but tried to solve them nonetheless.

PS: the PR's commit history looks embarassing (sorry about that), please "Squash and Merge" if the CI runs pass.

**Comment by AvinashReddy3108** [comment]
> The environment variables are there to provide an option to overwrite all this information. For example, imagine that when you are going to deploy the application in a productive environment you prefer to show the information of the company and not of the developer who implemented the application. In this way, unless overwritten, the package.json data will always be shown, but if we want others for any reason, they could be provided in a very simple way.

@borjapazr I also updated the `.env` file with the related variables (these are commented out by default)

But won't it be better if there's a `.env.sample` tracked by version control, and then `.env` in the `.gitignore` (As the `.env` contains sensitive info like database passwords and stuff)

**Review by borjapazr — APPROVED** [review]

**Pull request merged**
